In [1]:
import pandas as pd
import numpy as np

pd.set_option(
    "display.max_columns",
    None
)

In [2]:
incidents = pd.read_csv(
    "../data/incidents.csv"
)

airlines = pd.read_csv(
    "../data/airlines.csv"
)

aircraft = pd.read_csv(
    "../data/aircraft_types.csv"
)

routes = pd.read_csv(
    "../data/routes.csv"
)

trends = pd.read_csv(
    "../data/safety_trends.csv"
)

In [3]:
print(
    incidents.shape
)

print(
    airlines.shape
)

print(
    aircraft.shape
)

print(
    routes.shape
)

print(
    trends.shape
)

(25000, 29)
(113, 16)
(79, 16)
(5000, 17)
(55, 16)

In [4]:
incidents.head()

,incident_id,date,year,month,airline,airline_region,airline_country,aircraft_type,aircraft_category,manufacturer,aircraft_age_years,manufacture_year,departure_airport,arrival_airport,country,region,incident_type,phase_of_flight,weather_conditions,primary_cause,is_fatal,fatalities,occupants_onboard,injuries,hull_loss,damage_category,investigation_status,engines,seats_config
0,AV000001,2002-02-27,2002,2,Kenya Airways,Africa,Kenya,HAVILLAND Twin Otter,Turboprop,De Havilland,7,1995,RPVM,RPLL,Philippines,AsiaPacific,Cargo Issue,climb,VMC,loading error,0,0,5,0,0,NaN,Inconclusive,2,20
1,AV000002,1985-01-18,1985,1,TAP Air Portugal,Europe,Portugal,Boeing 777-300ER,Widebody,Boeing,13,2000,YYYY,ZZZZ,Poland,Europe,Engine Failure,cruise,IMC-Fog,manufacturing,0,0,311,51,0,Minor,Probable cause determined,2,396
2,AV000003,2008-08-23,2008,8,American Airlines,NorthAmerica,USA,Boeing 767-400,Widebody,Boeing,21,1990,KLAX,KSFO,USA,NorthAmerica,Controlled Flight into Terrain (CFIT),cruise,IMC-Low,crew error,1,183,245,0,1,Destroyed,Probable cause determined,2,245
3,AV000004,1997-12-28,1997,12,ASKY Airlines,Africa,Togo,Fokker 100,Regional,Fokker,14,1983,KJFK,KMIA,USA,NorthAmerica,Controlled Flight into Terrain (CFIT),descent,VMC,navigation,0,0,45,9,0,Minor,Inconclusive,2,107
4,AV000005,1973-08-05,1973,8,Air France,Europe,France,Boeing 720,Narrowbody,Boeing,10,1963,VNKT,VNPL,Nepal,SouthAsia,Icing,approach,VMC,weather,1,40,127,0,1,Destroyed,Probable cause determined,4,149

In [5]:
incidents.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   incident_id           25000 non-null  str
 1   date                  25000 non-null  str
 2   year                  25000 non-null  int64
 3   month                 25000 non-null  int64
 4   airline               25000 non-null  str
 5   airline_region        25000 non-null  str
 6   airline_country       25000 non-null  str
 7   aircraft_type         25000 non-null  str
 8   aircraft_category     25000 non-null  str
 9   manufacturer          25000 non-null  str
 10  aircraft_age_years    25000 non-null  int64
 11  manufacture_year      25000 non-null  int64
 12  departure_airport     25000 non-null  str
 13  arrival_airport       25000 non-null  str
 14  country               25000 non-null  str
 15  region                25000 non-null  str
 16  incident_type         25000 non-null  str
 17  phase_of_flight       25000 non-null  str
 18  weather_conditions    25000 non-null  str
 19  primary_cause         25000 non-null  str
 20  is_fatal              25000 non-null  int64
 21  fatalities            25000 non-null  int64
 22  occupants_onboard     25000 non-null  int64
 23  injuries              25000 non-null  int64
 24  hull_loss             25000 non-null  int64
 25  damage_category       23388 non-null  str
 26  investigation_status  25000 non-null  str
 27  engines               25000 non-null  int64
 28  seats_config          25000 non-null  int64
dtypes: int64(11), str(18)
memory usage: 5.5 MB

In [6]:
incidents.describe(
    include="all"
)

,incident_id,date,year,month,airline,airline_region,airline_country,aircraft_type,aircraft_category,manufacturer,aircraft_age_years,manufacture_year,departure_airport,arrival_airport,country,region,incident_type,phase_of_flight,weather_conditions,primary_cause,is_fatal,fatalities,occupants_onboard,injuries,hull_loss,damage_category,investigation_status,engines,seats_config
count,25000,25000,25000.00000,25000.000000,25000,25000,25000,25000,25000,25000,25000.000000,25000.000000,25000,25000,25000,25000,25000,25000,25000,25000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,23388,25000,25000.00000,25000.000000
unique,25000,12870,NaN,NaN,112,9,61,79,7,31,NaN,NaN,129,129,57,9,16,8,6,21,NaN,NaN,NaN,NaN,NaN,3,5,NaN,NaN
top,AV000001,1974-11-10,NaN,NaN,Ural Airlines,Europe,USA,COMAC C919,Narrowbody,Boeing,NaN,NaN,YYYY,ZZZZ,Mexico,NorthAmerica,Loss of Control - Inflight (LOC-I),cruise,VMC,crew error,NaN,NaN,NaN,NaN,NaN,Minor,Probable cause determined,NaN,NaN
freq,1,8,NaN,NaN,426,7902,2246,355,9017,6043,NaN,NaN,3034,3034,2547,7399,3789,5348,9620,6400,NaN,NaN,NaN,NaN,NaN,14288,11238,NaN,NaN
mean,NaN,NaN,1990.21160,6.486240,NaN,NaN,NaN,NaN,NaN,NaN,11.556200,1990.350240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.302160,12.950240,114.382160,9.313240,0.352760,NaN,NaN,2.36412,151.277360
std,NaN,NaN,14.29522,3.450236,NaN,NaN,NaN,NaN,NaN,NaN,5.864767,14.317548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.459203,37.177641,90.364755,13.899354,0.477838,NaN,NaN,0.76344,114.222083
min,NaN,NaN,1970.00000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1946.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,0.000000,0.000000,NaN,NaN,1.00000,9.000000
25%,NaN,NaN,1978.00000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,1980.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,47.000000,0.000000,0.000000,NaN,NaN,2.00000,70.000000
50%,NaN,NaN,1988.00000,6.000000,NaN,NaN,NaN,NaN,NaN,NaN,11.000000,1990.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,97.000000,3.000000,0.000000,NaN,NaN,2.00000,130.000000
75%,NaN,NaN,2000.00000,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,16.000000,2000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,4.000000,155.000000,14.000000,1.000000,NaN,NaN,2.00000,181.000000
max,NaN,NaN,2024.00000,12.000000,NaN,NaN,NaN,NaN,NaN,NaN,39.000000,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,526.000000,555.000000,112.000000,1.000000,NaN,NaN,4.00000,555.000000

In [7]:
incidents.isnull().sum()

incident_id                0
date                       0
year                       0
month                      0
airline                    0
airline_region             0
airline_country            0
aircraft_type              0
aircraft_category          0
manufacturer               0
aircraft_age_years         0
manufacture_year           0
departure_airport          0
arrival_airport            0
country                    0
region                     0
incident_type              0
phase_of_flight            0
weather_conditions         0
primary_cause              0
is_fatal                   0
fatalities                 0
occupants_onboard          0
injuries                   0
hull_loss                  0
damage_category         1612
investigation_status       0
engines                    0
seats_config               0
dtype: int64