In [5]:
import sys
import os

sys.path.append(
    os.path.abspath("..")
)

In [6]:
from src.airline_analysis import AirlineAnalysis

In [7]:
import pandas as pd

df = pd.read_csv(
    "../data/incidents.csv"
)

df.head()

,incident_id,date,year,month,airline,airline_region,airline_country,aircraft_type,aircraft_category,manufacturer,...,primary_cause,is_fatal,fatalities,occupants_onboard,injuries,hull_loss,damage_category,investigation_status,engines,seats_config
0,AV000001,2002-02-27,2002,2,Kenya Airways,Africa,Kenya,HAVILLAND Twin Otter,Turboprop,De Havilland,...,loading error,0,0,5,0,0,NaN,Inconclusive,2,20
1,AV000002,1985-01-18,1985,1,TAP Air Portugal,Europe,Portugal,Boeing 777-300ER,Widebody,Boeing,...,manufacturing,0,0,311,51,0,Minor,Probable cause determined,2,396
2,AV000003,2008-08-23,2008,8,American Airlines,NorthAmerica,USA,Boeing 767-400,Widebody,Boeing,...,crew error,1,183,245,0,1,Destroyed,Probable cause determined,2,245
3,AV000004,1997-12-28,1997,12,ASKY Airlines,Africa,Togo,Fokker 100,Regional,Fokker,...,navigation,0,0,45,9,0,Minor,Inconclusive,2,107
4,AV000005,1973-08-05,1973,8,Air France,Europe,France,Boeing 720,Narrowbody,Boeing,...,weather,1,40,127,0,1,Destroyed,Probable cause determined,4,149

In [8]:
AirlineAnalysis.airline_incidents(
    df
)

                   airline  incident_count
103          Ural Airlines             426
77             S7 Airlines             253
60                Lion Air             251
74        Rossiya Airlines             250
37                  Cubana             248
..                     ...             ...
73           Qatar Airways             196
80   Scandinavian Airlines             193
98            Thai Airways             191
109               Wizz Air             190
44               Eurowings             185

[112 rows x 2 columns]

In [9]:
AirlineAnalysis.airline_fatalities(
    df
)

                   airline  fatalities
103          Ural Airlines        7151
97                   Tarom        5103
67         Olympic Airways        5050
14               Air Koryo        4885
37                  Cubana        4832
..                     ...         ...
80   Scandinavian Airlines        1674
38         Delta Air Lines        1592
73           Qatar Airways        1589
72                  Qantas        1472
27         British Airways        1192

[112 rows x 2 columns]